/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.server.forme;

import rs.ac.bg.fon.server.server.Server;

/**
 * Glavna grafička forma serverskog dela aplikacije (JFrame).
 * Predstavlja kontrolnu tablu preko koje korisnik (administrator) može da pokreće i zaustavlja 
 * centralni aplikacioni server (serversku nit) i prati trenutni status sistema, kao i da otvara forme za konfiguraciju.
 *
 * @author Damjan
 */
public class ServerskaForma extends javax.swing.JFrame {
    /**
     * Referenca na serversku nit koja osluškuje i prihvata klijentske zahteve.
     */
    private Server server;
    /**
     * Kreira novu ServerskaForma, inicijalizuje grafičke komponente, kreira objekat 
     * Server i inicijalno onemogućava dugme za zaustavljanje jer server startuje u ugašenom stanju.
     */
    public ServerskaForma() {
        initComponents();
        server = new Server();
        jButtonZaustavi.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jButtonZaustavi = new javax.swing.JButton();
        jButtonPokreni = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonZaustavi.setText("Zaustavi server");
        jButtonZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZaustaviActionPerformed(evt);
            }
        });

        jButtonPokreni.setText("Pokreni server");
        jButtonPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPokreniActionPerformed(evt);
            }
        });

        jLabelStatus.setText("Server nije pokrenut");

        jMenu1.setText("Konfiguracija");

        jMenuItem1.setText("baza");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonZaustavi)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabelStatus)
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(jButtonPokreni)
                    .addContainerGap(195, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jButtonZaustavi)
                .addGap(26, 26, 26)
                .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jButtonPokreni)
                    .addContainerGap(113, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Akciona metoda koja otvara modalni dijalog za konfigurisanje parametara konekcije sa bazom podataka.
     *
     * @param evt Objekat akcionog događaja.
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       KonfiguracijaBazeForma baza = new KonfiguracijaBazeForma(this, false);
       baza.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    /**
     * Akciona metoda zadužena za pokretanje aplikacionog servera. Ukoliko server nit ne postoji ili nije 
     * aktivna, kreira se nova instanca niti, startuje se i ažurira se vizuelni status na formi.
     *
     * @param evt Objekat akcionog događaja.
     */
    private void jButtonPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPokreniActionPerformed
        if (server == null || !server.isAlive()){
            server = new Server();
            server.start();
            jLabelStatus.setText("Server je pokrenut");
            jButtonPokreni.setEnabled(false);
            jButtonZaustavi.setEnabled(true);
        }
        
    }//GEN-LAST:event_jButtonPokreniActionPerformed
    /**
     * Akciona metoda zadužena za bezbedno zaustavljanje i gašenje aplikacionog servera. Poziva metodu za prekid 
     * osluškivanja unutar niti servera, uništava referencu i osvežava stanje grafičkih kontrola.
     *
     * @param evt Objekat akcionog događaja.
     */
    private void jButtonZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZaustaviActionPerformed
        if (server != null && server.isAlive()){
            server.zaustaviServer();
            server = null;
            jLabelStatus.setText("Server je zaustavljen");
            jButtonPokreni.setEnabled(true);
            jButtonZaustavi.setEnabled(false);
        }
        
    }//GEN-LAST:event_jButtonZaustaviActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPokreni;
    private javax.swing.JButton jButtonZaustavi;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
