/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.klijent.forme;

/**
 * Predstavlja grafički korisnički interfejs (JFrame) za kreiranje i unos novog 
 * zapisa o iznajmljivanju u sistemu.
 * <p>
 * Forma služi kao pogled (View) unutar klijentskog dela aplikacije i dizajnirana je tako da 
 * kroz javne metode i getter-e izlaže svoje vizuelne komponente (tabelu stavki, tekstualna polja, 
 * padajuće menije) kontroleru koji upravlja njenom poslovnom logikom i mrežnim zahtevima.
 * </p>
 *
 * @author Damjan
 */
public class DodajZapisForma extends javax.swing.JFrame {

    /**
     * Kreira novu instancu forme DodajZapisForma.
     * Unutar konstruktora se poziva automatski generisana metoda initComponents()
     * koja inicijalizuje, raspoređuje i pozicionira sve komponente korisničkog interfejsa.
     */
    public DodajZapisForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
