/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.klijent.forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 * Predstavlja grafički korisnički interfejs za unos novog sertifikata u sistem.
 * <p>
 * Forma obezbeđuje tekstualna polja za unos naziva sertifikata i institucije koja ga izdaje,
 * kao i dugme za potvrdu unosa. Dizajnirana je tako da kroz javne getter metode izlaže 
 * svoje komponente i omogućava kontroleru registraciju logike za obradu događaja.
 * </p>
 *
 * @author Damjan
 */
public class DodajSertifikatForma extends javax.swing.JFrame {

    /**
     * Kreira novu instancu forme DodajSertifikatForma.
     * Unutar konstruktora se poziva automatski generisana metoda initComponents()
     * koja pozicionira i inicijalizuje sve vizuelne komponente na formi.
     */
    public DodajSertifikatForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldInstitucija = new javax.swing.JTextField();
        jButtonDodaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DODAJ SERTIFIKAT");

        jLabel2.setText("Naziv:");

        jLabel3.setText("Institucija: ");

        jButtonDodaj.setText("Dodaj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonDodaj)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldInstitucija, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInstitucija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButtonDodaj)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldInstitucija;
    private javax.swing.JTextField jTextFieldNaziv;
    // End of variables declaration//GEN-END:variables

    /**
     * Vraća komponentu dugmeta namenjenu za pokretanje akcije dodavanja sertifikata.
     *
     * @return JButton Komponenta dugmeta "Dodaj".
     */
    public JButton getjButtonDodaj() {
        return jButtonDodaj;
    }

    /**
     * Vraća tekstualno polje namenjeno za unos ili prikaz institucije koja izdaje sertifikat.
     *
     * @return JTextField Komponenta za unos institucije.
     */
    public JTextField getjTextFieldInstitucija() {
        return jTextFieldInstitucija;
    }

    /**
     * Vraća tekstualno polje namenjeno za unos ili prikaz zvaničnog naziva sertifikata.
     *
     * @return JTextField Komponenta za unos naziva.
     */
    public JTextField getjTextFieldNaziv() {
        return jTextFieldNaziv;
    }

    /**
     * Registruje prosleđeni ActionListener na dugme "Dodaj".
     * Koristi se od strane odgovarajućeg kontrolera kako bi se mapirala i izvršila logika 
     * validacije i slanja podataka o sertifikatu ka serveru.
     *
     * @param actionListener Osluškivač događaja koji će se aktivirati klikom na dugme.
     */
    public void dodajActionListener(ActionListener actionListener) {
        jButtonDodaj.addActionListener(actionListener);
    }

}
