/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.klijent.forme;

import rs.ac.bg.fon.klijent.glavnikontroler.GlavniKontroler;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import rs.ac.bg.fon.zajednicki.model.Bibliotekar;
import rs.ac.bg.fon.zajednicki.model.Citalac;
import rs.ac.bg.fon.zajednicki.model.Knjiga;


/**
 * Predstavlja glavnu grafičku formu klijentske aplikacije.
 * <p>
 * Ova forma omogućava upravljanje i evidenciju zapisa o iznajmljivanju knjiga (unos, izmena, 
 * dodavanje i brisanje stavki unutar tabele), kao i navigaciju kroz aplikaciju putem 
 * glavnog menija (JMenuBar) koji komunicira direktno sa GlavniKontroler-om.
 * </p>
 * <p>
 * Dizajnirana je bez direktne biznis logike i kroz javne metode izlaže komponente 
 * kontroleru za potrebe manipulacije podacima i registracije osluškivača.
 * </p>
 *
 * @author Damjan
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Kreira novu instancu klase GlavnaForma.
     * Poziva automatski generisanu metodu initComponents() za inicijalizaciju 
     * rasporeda i svih vizuelnih komponenti na prozoru.
     */
    public GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabelKorisnicko = new javax.swing.JLabel();
        jTextFieldDatum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUkupanIznos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxCitalac = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldMaksDatumVracanja = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxKnjiga = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxKolicina = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldDatumVracanja = new javax.swing.JTextField();
        jButtonDodaj = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStavke = new javax.swing.JTable();
        jButtonKreiraj = new javax.swing.JButton();
        jButtonIzmeniZapis = new javax.swing.JButton();
        jComboBoxBibliotekari = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Zdravo:");

        jLabel2.setText("Datum:");

        jLabel3.setText("Ukupan iznos:");

        jTextFieldUkupanIznos.setEditable(false);

        jLabel4.setText("Bibliotekar:");

        jLabel5.setText("Citalac:");

        jLabel6.setText("Stavke zapisa o iznajmljivanju:");

        jLabel7.setText("Maks datum vracanja:");

        jLabel8.setText("Knjiga:");

        jLabel9.setText(" Kolicina:");

        jComboBoxKolicina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jComboBoxKolicina.setToolTipText("");

        jLabel10.setText("Datum vracanja:");

        jButtonDodaj.setText("Dodaj");

        jButtonObrisi.setText("Obrisi");

        jTableStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableStavke);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBoxKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jTextFieldMaksDatumVracanja, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDatumVracanja, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jComboBoxKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonObrisi)
                    .addComponent(jButtonDodaj))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDodaj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxKnjiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMaksDatumVracanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDatumVracanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonObrisi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jButtonKreiraj.setText("Kreiraj Zapis");

        jButtonIzmeniZapis.setText("Izmeni Zapis");

        jMenu1.setText("Citalac");

        jMenuItem1.setText("Dodaj");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Prikaz");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Sertifikat");

        jMenuItem5.setText("Dodaj");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Zapis o iznajmljivanju");

        jMenuItem7.setText("Prikaz");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelKorisnicko))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jTextFieldUkupanIznos))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxCitalac, 0, 151, Short.MAX_VALUE)
                            .addComponent(jComboBoxBibliotekari, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonKreiraj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIzmeniZapis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelKorisnicko))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxBibliotekari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxCitalac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonIzmeniZapis)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonKreiraj)
                        .addGap(40, 40, 40))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        GlavniKontroler.getInstanca().otvoriPrikazCitalacaFormu();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        GlavniKontroler.getInstanca().otvoriDodajSertifikatFormu();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        GlavniKontroler.getInstanca().otvoriDodajCitaocaFormu();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        GlavniKontroler.getInstanca().otvoriPrikazZapisaFormu();
    }//GEN-LAST:event_jMenuItem7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonIzmeniZapis;
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JComboBox<Bibliotekar> jComboBoxBibliotekari;
    private javax.swing.JComboBox<Citalac> jComboBoxCitalac;
    private javax.swing.JComboBox<Knjiga> jComboBoxKnjiga;
    private javax.swing.JComboBox<String> jComboBoxKolicina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelKorisnicko;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStavke;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldDatumVracanja;
    private javax.swing.JTextField jTextFieldMaksDatumVracanja;
    private javax.swing.JTextField jTextFieldUkupanIznos;
    // End of variables declaration//GEN-END:variables

    /**
     * Vraća komponentu natpisa (JLabel) zaduženu za prikaz korisničkog imena 
     * trenutno ulogovanog bibliotekara.
     *
     * @return JLabel Komponenta za prikaz imena korisnika.
     */
    public JLabel getjLabelKorisnicko() {
        return jLabelKorisnicko;
    }

    /**
     * Vraća padajući meni koji sadrži listu svih čitalaca registrovanih u sistemu.
     *
     * @return JComboBox Komponenta sa objektima tipa Citalac.
     */
    public JComboBox<Citalac> getjComboBoxCitalac() {
        return jComboBoxCitalac;
    }

    /**
     * Vraća padajući meni koji sadrži listu svih dostupnih knjiga za iznajmljivanje.
     *
     * @return JComboBox Komponenta sa objektima tipa Knjiga.
     */
    public JComboBox<Knjiga> getjComboBoxKnjiga() {
        return jComboBoxKnjiga;
    }

    /**
     * Vraća komponentu tabele u kojoj su tabelarno prikazane dodate stavke 
     * trenutnog zapisa o iznajmljivanju.
     *
     * @return JTable Komponenta za prikaz stavki zapisa.
     */
    public JTable getjTableStavke() {
        return jTableStavke;
    }

    /**
     * Vraća padajući meni sa listom bibliotekara u sistemu.
     *
     * @return JComboBox Komponenta sa objektima tipa Bibliotekar.
     */
    public JComboBox<Bibliotekar> getjComboBoxBibliotekari() {
        return jComboBoxBibliotekari;
    }

    /**
     * Vraća tekstualno polje namenjeno za unos ili prikaz datuma kreiranja zapisa.
     *
     * @return JTextField Komponenta za unos datuma zapisa.
     */
    public JTextField getjTextFieldDatum() {
        return jTextFieldDatum;
    }

    /**
     * Vraća padajući meni namenjen za odabir količine primeraka izabrane knjige.
     *
     * @return JComboBox Komponenta sa tekstualnim vrednostima količine.
     */
    public JComboBox<String> getjComboBoxKolicina() {
        return jComboBoxKolicina;
    }

    /**
     * Vraća tekstualno polje namenjeno za unos datuma kada čitalac vraća knjigu.
     *
     * @return JTextField Komponenta za unos datuma vraćanja.
     */
    public JTextField getjTextFieldDatumVracanja() {
        return jTextFieldDatumVracanja;
    }

    /**
     * Vraća tekstualno polje koje prikazuje maksimalno dozvoljeni rok/datum za vraćanje knjige.
     *
     * @return JTextField Komponenta za prikaz maksimalnog roka.
     */
    public JTextField getjTextFieldMaksDatumVracanja() {
        return jTextFieldMaksDatumVracanja;
    }

    /**
     * Vraća tekstualno polje koje prikazuje ukupnu kalkulisanu cenu/iznos za sve unete stavke.
     * Polje je podrazumevano zaključano za ručne izmene.
     *
     * @return JTextField Komponenta za prikaz ukupnog iznosa.
     */
    public JTextField getjTextFieldUkupanIznos() {
        return jTextFieldUkupanIznos;
    }

    /**
     * Registruje prosleđeni ActionListener na dugme "Dodaj" unutar panela za stavke.
     * Koristi se za dodavanje nove pojedinačne stavke u tabelu tekućeg zapisa.
     *
     * @param actionListener Osluškivač događaja koji će se aktivirati klikom na dugme.
     */
    public void addDodajActionListener(ActionListener actionListener){
        jButtonDodaj.addActionListener(actionListener);
    }
    
    /**
     * Registruje prosleđeni ActionListener na dugme "Obrisi" unutar panela za stavke.
     * Koristi se za uklanjanje selektovane stavke iz tabele.
     *
     * @param actionListener Osluškivač događaja koji će se aktivirati klikom na dugme.
     */
    public void addObrisiActionListener(ActionListener actionListener){
        jButtonObrisi.addActionListener(actionListener);
    }

    /**
     * Registruje prosleđeni ActionListener na dugme "Kreiraj Zapis".
     * Koristi se od strane kontrolera kako bi se pokrenula procedura perzistencije celokupnog 
     * zapisa sa svim stavkama na serveru.
     *
     * @param actionListener Osluškivač događaja koji će se aktivirati klikom na dugme.
     */
    public void addKreirajActionListener(ActionListener actionListener){
        jButtonKreiraj.addActionListener(actionListener);
    }

    /**
     * Registruje prosleđeni ActionListener na dugme "Izmeni Zapis".
     * Koristi se za pokretanje procedure ažuriranja postojećeg zapisa o iznajmljivanju u bazi podataka.
     *
     * @param actionListener Osluškivač događaja koji će se aktivirati klikom na dugme.
     */
    public void addIzmeniActionListener(ActionListener actionListener) {
        jButtonIzmeniZapis.addActionListener(actionListener);
    }

    /**
     * Vraća komponentu dugmeta namenjenu za izvršavanje i potvrdu izmene zapisa.
     *
     * @return JButton Komponenta dugmeta "Izmeni Zapis".
     */
    public JButton getjButtonIzmeniZapis() {
        return jButtonIzmeniZapis;
    }

    /**
     * Vraća komponentu dugmeta namenjenu za izvršavanje i potvrdu kreiranja novog zapisa.
     *
     * @return JButton Komponenta dugmeta "Kreiraj Zapis".
     */
    public JButton getjButtonKreiraj() {
        return jButtonKreiraj;
    }
    
}
