/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.klijent.forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 * Predstavlja grafički korisnički interfejs (JFrame) za autentifikaciju korisnika na sistem.
 * <p>
 * Forma obezbeđuje unos korisničkog imena kroz tekstualno polje i lozinke kroz zaštićeno polje,
 * kao i dugme za pokretanje procesa prijave. Dizajnirana je po MVP/MVC šablonu tako da kroz 
 * javne getter i setter metode omogućava kontroleru pristup unetim podacima i upravljanje stanjem 
 * njenih vizuelnih komponenti.
 * </p>
 *
 * @author Damjan
 */
public class LoginForma extends javax.swing.JFrame {

    /**
     * Kreira novu instancu forme LoginForma.
     * Unutar konstruktora se poziva automatski generisana metoda initComponents()
     * koja inicijalizuje elemente korisničkog interfejsa i postavlja podrazumevane test vrednosti.
     */
    public LoginForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldKorisnickoIme = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordFieldSifra = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Korisnicko ime:");

        jLabel2.setText("Sifra:");

        jTextFieldKorisnickoIme.setText("marko");

        jButton1.setText("Prijavi se");

        jPasswordFieldSifra.setText("marko");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldKorisnickoIme)
                            .addComponent(jPasswordFieldSifra, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordFieldSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordFieldSifra;
    private javax.swing.JTextField jTextFieldKorisnickoIme;
    // End of variables declaration//GEN-END:variables

   /**
     * Vraća instancu dugmeta zaduženog za slanje zahteva za prijavu na sistem.
     *
     * @return JButton Komponenta dugmeta "Prijavi se".
     */
    public JButton getjButton1() {
        return jButton1;
    }

    /**
     * Postavlja novu instancu dugmeta za prijavu.
     *
     * @param jButton1 Nova instancu dugmeta tipa JButton.
     */
    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    /**
     * Vraća komponentu polja za unos lozinke koja sakriva uneti tekst.
     *
     * @return JPasswordField Komponenta za bezbedan unos šifre.
     */
    public JPasswordField getjPasswordFieldSifra() {
        return jPasswordFieldSifra;
    }

    /**
     * Postavlja komponentu polja za lozinku.
     *
     * @param jPasswordFieldSifra Nova instanca komponente JPasswordField.
     */
    public void setjPasswordFieldSifra(JPasswordField jPasswordFieldSifra) {
        this.jPasswordFieldSifra = jPasswordFieldSifra;
    }

    /**
     * Vraća tekstualno polje namenjeno za unos korisničkog imena.
     *
     * @return JTextField Komponenta tekstualnog polja za korisničko ime.
     */
    public JTextField getjTextFieldKorisnickoIme() {
        return jTextFieldKorisnickoIme;
    }

    /**
     * Postavlja tekstualno polje za korisničko ime.
     *
     * @param jTextFieldKorisnickoIme Nova instanca komponente JTextField.
     */
    public void setjTextFieldKorisnickoIme(JTextField jTextFieldKorisnickoIme) {
        this.jTextFieldKorisnickoIme = jTextFieldKorisnickoIme;
    }

    /**
     * Registruje prosleđeni ActionListener na dugme za prijavu.
     * Povezuje se sa kontrolerom zaduženim za logovanje kako bi presreo klik korisnika, 
     * pokrenuo validaciju polja i prosledio kredencijale serveru na proveru.
     *
     * @param actionListener Osluškivač događaja koji implementira logiku prijave.
     */
    public void loginAddActionListener(ActionListener actionListener) {
        jButton1.addActionListener(actionListener);
    }
}

