/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.klijent.forme;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import rs.ac.bg.fon.zajednicki.model.Mesto;

/**
 * Predstavlja grafički korisnički interfejs (JFrame) za prikaz, pretragu i administraciju čitalaca.
 * <p>
 * Ova forma omogućava pretraživanje baze podataka čitalaca kombinovanjem filtera za ime, 
 * prezime i mesto. Rezultati se prikazuju unutar tabele, a forma pruža opcije za brisanje 
 * selektovanog čitaoca, izmenu njegovih podataka ili prikaz detaljnih informacija.
 * </p>
 * <p>
 * Prati MVP/MVC arhitekturni šablon, gde su sve komponente izložene putem javnih getter metoda, 
 * a registracija događaja se delegira odgovarajućem kontroleru.
 * </p>
 *
 * @author Damjan
 */
public class PrikazCitalacaForma extends javax.swing.JFrame {

    /**
     * Kreira novu instancu forme PrikazCitalacaForma.
     * Poziva automatski generisanu metodu initComponents() za inicijalizaciju 
     * rasporeda prozora i svih vizuelnih komponenti.
     */
    public PrikazCitalacaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCitaoci = new javax.swing.JTable();
        jButtonObrisi = new javax.swing.JButton();
        jButtonIzmeni = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxMesta = new javax.swing.JComboBox<>();
        jButtonPretrazi = new javax.swing.JButton();
        jButtonDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableCitaoci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCitaoci);

        jButtonObrisi.setText("Obrisi");

        jButtonIzmeni.setText("Izmeni");

        jLabel1.setText("Pretraga po imenu:");

        jLabel2.setText("Pretraga po prezimenu:");

        jLabel3.setText("Pretraga po mestu:");

        jButtonPretrazi.setText("Pretrazi");

        jButtonDetalji.setText("Detalji");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDetalji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPrezime)
                        .addComponent(jComboBoxMesta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldIme)
                        .addComponent(jButtonObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonIzmeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(9, 9, 9))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxMesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPretrazi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonObrisi)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonIzmeni)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDetalji)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetalji;
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JComboBox<Mesto> jComboBoxMesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCitaoci;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables

    /**
     * Vraća komponentu tabele (JTable) u kojoj su prikazani učitani i filtrirani čitaoci.
     *
     * @return JTable Komponenta za tabelarni prikaz čitalaca.
     */
    public JTable getjTableCitaoci() {
        return jTableCitaoci;
    }

    /**
     * Vraća komponentu dugmeta za brisanje selektovanog čitaoca.
     *
     * @return JButton Komponenta dugmeta "Obrisi".
     */
    public JButton getjButtonObrisi() {
        return jButtonObrisi;
    }

    /**
     * Registruje prosleđeni ActionListener na dugme "Obrisi".
     * Koristi se za pokretanje sistemske operacije uklanjanja selektovanog čitaoca iz baze.
     *
     * @param actionListener Osluškivač događaja za brisanje čitaoca.
     */
    public void addDugmeObrisiActionListener(ActionListener actionListener) {
        jButtonObrisi.addActionListener(actionListener);
    }
    
    /**
     * Registruje prosleđeni ActionListener na dugme "Izmeni".
     * Aktivira se kada kontroler treba da otvori formu za izmenu nad odabranim čitaocem.
     *
     * @param actionListener Osluškivač događaja za izmenu čitaoca.
     */
    public void addDugmeIzmeniActionListener(ActionListener actionListener) {
        jButtonIzmeni.addActionListener(actionListener);
    }
    
    /**
     * Registruje prosleđeni ActionListener na dugme "Pretrazi".
     * Koristi se za čitanje unetih parametara u tekstualnim poljima i ponovno filtriranje tabele.
     *
     * @param actionListener Osluškivač događaja za pokretanje pretrage.
     */
    public void addDugmePretraziActionListener(ActionListener actionListener) {
        jButtonPretrazi.addActionListener(actionListener);
    }
    
    /**
     * Registruje prosleđeni ActionListener na dugme "Detalji".
     * Služi za otvaranje detaljnog pregleda podataka o selektovanom čitaocu u read-only modifikaciji.
     *
     * @param actionListener Osluškivač događaja za prikaz detalja čitaoca.
     */
    public void addDugmeDetaljiActionListener(ActionListener actionListener){
        jButtonDetalji.addActionListener(actionListener);
    }
    
    /**
     * Vraća padajući meni (JComboBox) koji sadrži listu objekata tipa Mesto
     * iskorišćenih kao parametar pretrage.
     *
     * @return JComboBox Padajući meni sa geografskim mestima.
     */
    public JComboBox<Mesto> getjComboBoxMesta() {
        return jComboBoxMesta;
    }

    /**
     * Vraća tekstualno polje namenjeno za unos imena čitaoca (ili dela imena) radi filtriranja.
     *
     * @return JTextField Komponenta za unos kriterijuma imena.
     */
    public JTextField getjTextFieldIme() {
        return jTextFieldIme;
    }

    /**
     * Vraća tekstualno polje namenjeno za unos prezimena čitaoca radi filtriranja.
     *
     * @return JTextField Komponenta za unos kriterijuma prezimena.
     */
    public JTextField getjTextFieldPrezime() {
        return jTextFieldPrezime;
    }
    
    

}
