/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.ac.bg.fon.klijent.forme;

import java.awt.event.ActionListener;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 * Predstavlja grafički korisnički interfejs (JFrame) za prikaz, pretragu i detaljan pregled 
 * zapisa o iznajmljivanju knjiga i njihovih stavki.
 * <p>
 * Forma implementira dve tabele:
 * <ul>
 * <li><b>Glavna tabela (Zapisi):</b> Prikazuje opšte informacije o iznajmljivanjima.</li>
 * <li><b>Pomoćna tabela (Stavke):</b> Prikazuje konkretne stavke za selektovani zapis iz glavne tabele.</li>
 * </ul>
 * <p>
 * Korisnik može filtrirati zapise unošenjem imena/prezimena čitaoca ili bibliotekara. 
 * Kontroler upravlja akcijama pretrage, izmene zapisa, kao i prikazivanja detalja.
 * </p>
 *
 * @author Damjan
 */
public class PrikazZapisaForma extends javax.swing.JFrame {

    /**
     * Kreira novu instancu forme PrikazZapisaForma.
     * Poziva metodu initComponents() koja je generisana od strane NetBeans GUI Builder-a
     * kako bi se inicijalizovale komponente i postavio raspored elemenata.
     */
    public PrikazZapisaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableZapisi = new javax.swing.JTable();
        jButtonPretrazi = new javax.swing.JButton();
        jButtonIzmeniRacun = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStavke = new javax.swing.JTable();
        jTextFieldCitalac = new javax.swing.JTextField();
        jTextFieldBibliotekar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonDetalji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableZapisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableZapisi);

        jButtonPretrazi.setText("Pretrazi");

        jButtonIzmeniRacun.setText("Izmeni");

        jTableStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableStavke);

        jLabel1.setText("Citalac:");

        jLabel2.setText("Bibliotekar:");

        jButtonDetalji.setText("Detalji");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldBibliotekar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCitalac, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jButtonPretrazi, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jButtonIzmeniRacun, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(jButtonDetalji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCitalac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBibliotekar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPretrazi)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonIzmeniRacun)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDetalji))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetalji;
    private javax.swing.JButton jButtonIzmeniRacun;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableStavke;
    private javax.swing.JTable jTableZapisi;
    private javax.swing.JTextField jTextFieldBibliotekar;
    private javax.swing.JTextField jTextFieldCitalac;
    // End of variables declaration//GEN-END:variables

    /**
     * Vraća glavnu tabelu koja sadrži listu svih krovnih zapisa o iznajmljivanju.
     * Kontroler osluškuje selekciju redova u ovoj tabeli kako bi ažurirao tabelu stavki.
     *
     * @return JTable Komponenta tabele sa zapisima o iznajmljivanju.
     */
    public JTable getjTableZapisi() {
        return jTableZapisi;
    }

    /**
     * Vraća pomoćnu tabelu namenjenu prijasu pojedinačnih stavki 
     * koje pripadaju trenutno selektovanom zapisu o iznajmljivanju.
     *
     * @return JTable Komponenta tabele sa stavkama selektovanog iznajmljivanja.
     */
    public JTable getjTableStavke() {
        return jTableStavke;
    }

    /**
     * Vraća tekstualno polje koje služi za unos kriterijuma pretrage po bibliotekaru 
     * koji je obradio iznajmljivanje.
     *
     * @return JTextField Komponenta tekstualnog polja za ime/prezime bibliotekara.
     */
    public JTextField getjTextFieldBibliotekar() {
        return jTextFieldBibliotekar;
    }

    /**
     * Vraća tekstualno polje koje služi za unos kriterijuma pretrage po čitaocu 
     * koji je iznajmio knjige.
     *
     * @return JTextField Komponenta tekstualnog polja za ime/prezime čitaoca.
     */
    public JTextField getjTextFieldCitalac() {
        return jTextFieldCitalac;
    }

    /**
     * Registruje prosleđeni ActionListener na dugme "Izmeni".
     * Aktivira se kada koordinator/kontroler treba da otvori prozor za modifikaciju 
     * odabranog zapisa o iznajmljivanju (ili računa).
     *
     * @param actionListener Osluškivač događaja za pokretanje izmene zapisa.
     */
    public void addIzmeniActionListener(ActionListener actionListener){
        jButtonIzmeniRacun.addActionListener(actionListener);
    }

    /**
     * Registruje prosleđeni ActionListener na dugme "Pretrazi".
     * Ovdje se pokreće proces filtriranja krovnih zapisa na osnovu vrednosti unetih u polja 
     * za čitaoca i bibliotekara.
     *
     * @param actionListener Osluškivač događaja za aktivaciju pretrage baze.
     */
    public void addDugmePretraziActionListener(ActionListener actionListener) {
        jButtonPretrazi.addActionListener(actionListener);
    }
    
    /**
     * Registruje prosleđeni ActionListener na dugme "Detalji".
     * Služi da se odabrani zapis otvori u zasebnom detaljnom prozoru, najčešće u režimu 
     * gde su polja onemogućena za direktnu izmenu.
     *
     * @param actionListener Osluškivač događaja za prikazivanje detaljnih informacija.
     */
    public void addDetaljiActionListener(ActionListener actionListener){
        jButtonDetalji.addActionListener(actionListener);
    }
    

}
